### ISSUE TITLE
Bundled api returns 404 for all routes

### ISSUE THREAD

**Issue by sheinze** [mnestix/mnestix-browser#22]
Hi,

## Pretext
as stated in the Readme, i set up the Tool using docker-compose. All containers are up and the next step is to upload an aas using the provided api.

## Problem
All routes for the api return 404 from the server side

## Example
Simple GET request to /shells route

Docker Log: 

![2024-07-04 15_32_23-mnestix-api - Container - Docker Desktop](https://github.com/mnestix/mnestix-browser/assets/7068676/101e23aa-73f7-4bd6-b638-e21cd245c271)

**Comment by hofermo** [comment]
Hi @sheinze,

thank you for your issue.
It looks like the request is missing something.
Due to the fact that our API encapsulates multiple BaSyx services (such as the repository and the registry) you have to specify where exactly you want to go.
For accessing the repository the call to the API must start with `/repo`
So when you want to get all shells of a repository try to call 
```
http://localhost:5064/repo/shells
```
We tried explaining this behaviour in the [DockerHub description of the API](https://hub.docker.com/r/mnestix/mnestix-api).

Could you try if this works and if the documentation is sufficient?

**Comment by sheinze** [comment]
Okay, error is on me, but in the readme, it is not clear, that the .../repo/... is needed:

![grafik](https://github.com/mnestix/mnestix-browser/assets/7068676/3250d7b4-2d5b-41ee-a9ab-68064eb1cfbd)
